# Generated by Django 5.1.4 on 2024-12-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyTasks',
            new_name='Task',
        ),
    ]
