# Generated by Django 5.1.4 on 2024-12-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytasks', '0002_rename_mytasks_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='UserTask',
        ),
    ]
